const mongoose = require('mongoose');

const appointmentSchema = new mongoose.Schema({
    patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    doctorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor', required: true },
    date: { type: Date, required: true },
    time: { type: String, required: true }, // e.g., "10:00 AM"
    status: {
        type: String,
        enum: ['Pending', 'Confirmed', 'Cancelled', 'Completed'],
        default: 'Pending'
    },
    symptoms: { type: String, required: true },
    aiSummary: { type: String }, // To store the summary generated by AI Engine
    createdAt: { type: Date, default: Date.now }
}, {
    collection: 'appointments'
});

module.exports = mongoose.model('Appointment', appointmentSchema);
